version: "3.9"

services:
  web:
    image: wordpress:latest
    restart: always
    container_name: wordpress
    ports:
    - 83:80
    environment:
      - DB_NAME=wordpress
      - DB_USER=admin
      - DB_PASS=admin
      - DB_HOST=mysql
    volumes:
      - wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=wordpress
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: